### ISSUE TITLE
Not resolvable python dependencies on Windows

### ISSUE THREAD

**Issue by andry81** [hartwork/svneverever#3]
For the python `3.7.x` at least these:

* fcntl
* termios

The first one can be workarounded with a bit of hack: 
https://stackoverflow.com/a/25471508/2672125

When the second one seems just not resolvable at all:
https://stackoverflow.com/questions/52062977/unable-to-import-termios-package

So, i don't see a way to use it from Windows.

**Comment by hartwork** [comment]
Please report back if you still have any issues.

**Comment by ShadowCreator250** [comment]
I could not install the SourceForge pysvn lib because it only provides an install exe for Windows, which I cannot execute (no admin rights or windows defender issues).
So I chose to run it in WSL (Ubuntu-24.04). I had to tinker quite a bit to get it working.

When I tried `pip install --user svneverever` inside WSL as per the README, I got `error: externally-managed-environment`. The description suggested using pipx.

`pipx install svneverever` went without a hitch.
`sudo apt install python3-svn -y` did too. That installs the package into `/usr/lib/python3/dist-packages/`

But now I had to figure out how to get the lib inside the venv created by pipx. `pipx inject` uses pip and I was not confident enough in my understanding of its function to simply pass it the `/usr/lib/python3/dist-packages/pysvn` directory, though I read somewhere that passing directories to it is theoretically possible.

Then, I found this section in the [SourceForge Sources TAR / INSTALL.html | pysvn-1.9.23.tar.gz](https://sourceforge.net/projects/pysvn/files/pysvn/V1.9.23/pysvn-1.9.23.tar.gz/download):
```
Install pysvn by copying the following from Extension/Source to python site-specific directory.
    mkdir python-libdir/site-packages/pysvn
    cp pysvn/__init__.py python-libdir/site-packages/pysvn
    cp pysvn/_pysvn*.so python-libdir/site-packages/pysvn
```
Doesn't hurt to try.
```bash
mkdir ~/.local/share/pipx/venvs/svneverever/lib/python3.12/site-packages/pysvn
cp /usr/lib/python3/dist-packages/pysvn/__init__.py ~/.local/share/pipx/venvs/svneverever/lib/python3.12/site-packages/pysvn
cp /usr/lib/python3/dist-packages/pysvn/_pysvn*.so ~/.local/share/pipx/venvs/svneverever/lib/python3.12/site-packages/pysvn
```
I also did
```bash
nano ~/.local/share/pipx/venvs/svneverever/pipx_metadata.json
```
and added this section into the `"injected_packages"` map:
```json
        "pysvn": {
            "app_paths": [],
            "app_paths_of_dependencies": {},
            "apps": [],
            "apps_of_dependencies": [],
            "include_apps": false,
            "include_dependencies": false,
            "man_pages": [],
            "man_pages_of_dependencies": [],
            "man_paths": [],
            "man_paths_of_dependencies": {},
            "package": "pysvn",
            "package_or_url": "_pysvn",
            "package_version": "1.9.22",
            "pip_args": [],
            "suffix": ""
        }
```
Which is not strictly necessary, but whatever.


And now my `svneverever` command seems to work.

**Comment by hartwork** [comment]
@ShadowCreator250 thanks for sharing your journey. I'm with you that pysvn is one annoying of a dependency 😞

**Comment by andry81** [comment]
@hartwork My journey ended with Git :laughing:

Details: https://stackoverflow.com/questions/42793618/svn-to-git-migration-with-nested-svnexternals/56649569#56649569
